### ISSUE TITLE
Namepaces not reloading and/or unclear docs

### ISSUE THREAD

**Issue by kamituel** [dgellow/boot-hiccup#1]
Any namespace one refers in `:files` option isn't reloaded properly. I.e. this task:

``` clojure
(deftask dev []
  (comp
   (watch)
   (hiccup :files {"index.html" 'some.ns/tmpl})
   (target)))
```

Creates "index.html" properly once, but then if I'd modify "some/ns.clj", it won't be recompiled, even though I use `(watch)`. That's because here: https://github.com/dgellow/boot-hiccup/blob/master/src/dgellow/boot_hiccup.clj#L45 namespace wouldn't be reloaded if it was already loaded once.

So either docs should mention that or, preferably, this library should reload namespaces correctly. Preferred way is how `boot-refresh` handles it (https://github.com/samestep/boot-refresh). 

Also, in an example, it'd be nice to mention `(target)` is needed if files are to be actually persisted.

**Comment by dgellow** [comment]
@kamituel I'm open to pull requests

**Comment by mikebelanger** [comment]
@kamituel by that, do you mean putting a `(refresh` invocation right before doing the hiccup compilation?  That works for me.

``` clojure
(deftask csshtml []
  (comp
    (watch)
    (refresh)
    (garden :styles-var 'home-page.style/screen)
    (hiccup :files {"index.html" 'home-page.core/index})
    (target)))
```
